name: Publish backend image & widget zip

on:
  push:
    branches: ["main"]     
    tags: ["v*"]             

permissions:
  contents: write            
  packages: write            

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # Cuando es push a main -> "latest" + nombre de rama
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Cuando es tag vX.Y.Z -> semver
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  widget-zip:
    name: Build & Attach Widget ZIP
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') 
    needs: docker
    steps:
      - uses: actions/checkout@v4

      - name: Create widget zip
        run: |
          cd zabbix-widget
          zip -r ../zabbix-widget-aimaintenance-${{ github.ref_name }}.zip aimaintenance
          ls -lh ../zabbix-widget-aimaintenance-${{ github.ref_name }}.zip

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            zabbix-widget-aimaintenance-${{ github.ref_name }}.zip
